version: '3'
services:

  mongodb:
    image: mongo
    ports:
      - 27017:27017

  MIC1:
     image: microservice1
     build: 
       context: ./Mic1
       dockerfile: Dockerfile
     ports:
       - 8091:8091
     network_mode: host
     depends_on:
       - mongodb

  MIC2:
     image: microservice2
     build:
       context: ./Mic2
       dockerfile: Dockerfile
     ports:
       - 8092:8092
     network_mode: host
     depends_on:
       - MIC1

  MIC3:
     image: microservice3
     build:
       context: ./Mic3
       dockerfile: Dockerfile
     ports:
       - 8093:8093
     network_mode: host
     depends_on:
       - MIC2
